server:
  port: 4200
okta:
  oauth2:
    issuer:
    client-id:
    pkce-always: true
    scopes:
      - openid
      - profile
      - email
    redirect-uri: /implicit/callback
logging:
  level:
    org:
      springframework:
        security: DEBUG
